// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var color;
    return color = ImageAnalyzer('sample.jpg', function(bgcolor, primaryColor, secondaryColor, detailColor) {
      $('#frame').css('background-color', 'rgb(' + bgcolor + ')');
      $('.primary').css('color', 'rgb(' + primaryColor + ')');
      $('.secondary').css('color', 'rgb(' + secodaryColor + ')');
      return $('.detail').css('color', 'rgb(' + detailColor + ')');
    });
  });

}).call(this);
